service: get-screenshot

provider:
  name: google
  runtime: nodejs8
  region: us-central1
  project: screenshot-compare
  credentials: ../../random/screenshot-compare-72877eb34d60.json # path must be absolute

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - .gitignore
    - .git/**
    - .gcloud/**

functions:
  get:
    handler: getScreenShot
    events:
      - event:
          eventType: google.pubsub.topic.publish
          resource: projects/screenshot-compare/topics/screenshot-created
# functions:
#   get:
#     handler: getScreenShot
#     events:
#       - event:
#         eventType: google.pubsub.topic.publish
#         resource: projects/screenshot-compare/topics/screenshot-created
        